enable: true
coreUrl: ws://127.0.0.1:8765
token: ""
reconnectInterval: 5000
reportPrivate: true
reportGroup: true
reportMeta: true
silentUnauthorized: false
masterBypassGroupDisabled: false
groupRules: {}
bots: {}